#!/bin/sh

#./TnPFitterScripter.sh GSFToISO HFSCToEID HFSCToEIDT SCToGSF GSFToISO80 ISOToID ISOToID80 IDToHLT IDToHLT80 GSFToWP95 GSFToWP90 GSFToWP85 GSFToWP80 GSFToWP70 GSFToWP60 SCToNTEID SCToNTEIDT GSFToInvWP80 SCToInvWP80 FINAL FHF FNTT MCToSC

./TnPFitterScripter.sh $1 GSFToISO HFSCToEID HFSCToEIDT SCToGSF GSFToISO80 ISOToID ISOToID80 IDToHLT IDToHLT80 GSFToWP95 GSFToWP90 GSFToWP85 GSFToWP80 GSFToWP70 GSFToWP60 SCToNTEID SCToNTEIDT GSFToInvWP80 SCToInvWP80 NTToInvWP80 HFToInvWP80 FINAL FHF FNTT INVFINAL INVFHF
